name: CI/CD Deployment for Personal Webpage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate HTML
        run: |
          sudo apt-get install -y tidy
          for file in $(find . -maxdepth 1 -name '*.html'); do
            tidy -q -e "$file" || true
          done

      - name: Validate CSS
        run: |
          npm install -g csslint
          csslint style.css || true

      - name: Output Validation Complete
        run: echo "HTML and CSS validated!"

  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
